package com.sanctionco.opconnect.model;

/**
 * Represents an item category.
 */
public enum Category {
  LOGIN,
  PASSWORD,
  SERVER,
  DATABASE,
  CREDIT_CARD,
  MEMBERSHIP,
  PASSPORT,
  SOFTWARE_LICENSE,
  OUTDOOR_LICENSE,
  SECURE_NOTE,
  WIRELESS_ROUTER,
  BANK_ACCOUNT,
  DRIVER_LICENSE,
  IDENTITY,
  REWARD_PROGRAM,
  DOCUMENT,
  EMAIL_ACCOUNT,
  SOCIAL_SECURITY_NUMBER,
  CUSTOM
}
